version: "3.1"

services:
  db:
    image: mariadb:10.5.3
    container_name: corporallancot.db
    ports:
      - "${DB_LOCAL_PORT}:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${DB_MOUNT_PATH}:/var/lib/mysql
      - ${DB_SQL_SCRIPTS_MOUNT_PATH}:/docker-entrypoint-initdb.d
  bot:
    image: corporallancot:latest
    container_name: corporallancot.bot
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - ${BOT_LOGS_MOUNT_PATH}:/bot/logs
